force-app/main/default/objects/Live_Engagement_Response__c/Live_Engagement_Response__c.object-meta.xml
<CustomObject>
    <label>Live Engagement Response</label>
    <nameField>
        <displayFormat>LER-{0000000}</displayFormat>
        <label>Live Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Engagement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Live_Engagement_Response__c/fields/TimeStamp__c.field-meta.xml
<CustomField>
    <fullName>TimeStamp__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>TimeStamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/PennyResponseWrapper.cls
global with sharing class PennyResponseWrapper implements Comparable
{
    public Live_Engagement_Response__c resp;
    // Constructor
    public PennyResponseWrapper(Live_Engagement_Response__c r) 
    {
        resp = r;
    }
    
    // Compare opportunities based on the opportunity amount.
    global Integer compareTo(Object compareTo) {
        // Cast argument to OpportunityWrapper
        PennyResponseWrapper compareToOppy = (PennyResponseWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if (resp.TimeStamp__c > compareToOppy.resp.TimeStamp__c) {
            // Set return value to a positive value.
            returnValue = 1;
        } else if (resp.TimeStamp__c < compareToOppy.resp.TimeStamp__c) {
            // Set return value to a negative value.
            returnValue = -1;
        }
        
        return returnValue;       
    }
}