force-app/main/default/objects/Live_Engagement_Response__c/Live_Engagement_Response__c.object-meta.xml
<CustomObject>
    <label>Live Engagement Response</label>
    <nameField>
        <displayFormat>LER-{0000000}</displayFormat>
        <label>Live Engagement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Engagement Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Live_Engagement_Response__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Live Engagement Responses</relationshipLabel>
    <relationshipName>Live_Engagement_Responses</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Engagement_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Message</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Live_Engagement_Response__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <formula>TEXT(Live_Engagement__r.Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PennyChatVFController.cls
public class PennyChatVFController 
{
    Private List<string> displayedIDs {get;set;}
    Public String outputChat{get;set;}
    
    public PennyChatVFController()
    {
        displayedIDs = new list<string>();
        //refreshData();
    }
    
    public void refreshData()
    {
        outputChat = '';
        List<Live_Engagement_Response__c> objResponses = new List<Live_Engagement_Response__c>([SELECT ID, Contact__r.Name, Response__c FROM Live_Engagement_Response__c WHERE isValid__c = true AND Type__c =:'Questions' ORDER BY CreatedDate DESC LIMIT 10]);
        if (objResponses.Size() > 0)
        {
            for (integer i = objResponses.Size()-1; i >=0 ; i--)
            {
                if (!displayedIDs.contains(String.valueof(objResponses[i].id)))
                {
                    displayedIDs.add(String.valueof(objResponses[i].id));
                    //outputChat =  String.valueof(displayedIDs[0]) + '|' + String.valueof(displayedIDs.size()) + ' - ' + String.valueof(objResponses[i].id);
                    outputChat += objResponses[i].Contact__r.Name.remove('|') + '|' + objResponses[i].Response__c.remove('|') + '#|#';
                    //return;
                }
            }
        }
        
    }
}